name:                haskell-conduit-example
version:             0.1.0.0
github:              "bhoudebert/haskell-conduit-example"
license:             GPL2

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- conduit

library:
  source-dirs: src

executables:
  haskell-conduit-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-conduit-example
    # Used for pagination


tests:
  haskell-conduit-example-test:
    main:                Main.hs
    source-dirs:         test
    default-extensions:
      - OverloadedStrings
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-conduit-example
      - hspec
      - QuickCheck
      - quickcheck-instances
      - generic-random
